name: Build and Test

on:
  push:
    branches:
    - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '19.x'

      - name: npm build and test
        run: |
          cd api
          npm install
          npm run build
          npm run test
          cd ..

          cd app
          npm install --legacy-peer-deps # until merged https://github.com/vuejs/eslint-config-standard/pull/12
          npm run build
          npm run test
          cd ..

          cd api
          nohup npm run start &
          cd ../app
          nohup npm run serve -- --port 8081 --public host.testcontainers.internal &
          cd tests/selenium
          mvn test
        env:
          DBHOST: localhost
          DBPORT: 6379

      - name: test report
        uses: dorny/test-reporter@v1
        if: ${{ always() }} # even if tests fail
        with:
          name: test report
          path: api/results/*.xml,app/results/*.xml
          reporter: java-junit # https://github.com/dorny/test-reporter/issues/154

      - name: upload cypress videos
        uses: actions/upload-artifact@v4
        with:
          name: cypress videos
          path: app/results/videos/*.mp4
      
      - name: upload selenium artifacts
        uses: actions/upload-artifact@v4
        with:
          name: selenium artifacts
          path: |
            app/tests/selenium/video/*.mp4


      # TODO: deploy
